name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: |
            package-lock.json
            web/package-lock.json
            sanity/package-lock.json

      - name: Install
        run: npm ci

      - name: Verify
        run: npm run verify
